### ISSUE TITLE
TraceRay.cs doesnt work

### ISSUE THREAD

**Issue by joshdixon** [BigMo/ZMH5_Helios#6]
Hey, I'm trying to utlilise the TraceRay IsVisible function but it doesn't seem to work. It always returns true when it shouldn't. I know this function isn't actually used in the program, but I am trying to use it for my demo viewer program as it is much more efficient. Any one see any obvious reasons why this function doesn't work?

**Comment by BigMo** [comment]
Hi, did you update all relevant offsets? Also please note that TraceRay only uses the BSP information (brushes) but not models. It will not register collisions with doors, windows, cars, furniture and most crates.

**Comment by joshdixon** [comment]
I'm not using any offsets as all I am doing is using the BSP parsing in conjunction with reading a demo file. I have a radar which shows the locations of all the players and they change colour if they are visible by a player on the enemy team. And when I use the traceray function they are always visible no matter what. When I use the default 1 unit stepping method it works fine, however this is really slow when parsing 128 tick demos that are over an hour long. Also I know about the static props, I already have them parsed and can check for collisions against them.
